plugins {
	id 'java'
	// apply false를 추가하여 루트에서는 실행하지 않고 하위 모듈에 플러그인을 배포만 함
	id 'org.springframework.boot' version '3.4.1' apply false
	id 'io.spring.dependency-management' version '1.1.7'
}

repositories {
	mavenCentral()
}

subprojects { // 모든 하위 모듈에 공통 적용할 설정
	group = 'com.finance'
	version = '1.0.0'

	apply plugin: 'java-library'
	apply plugin: 'io.spring.dependency-management'

	dependencyManagement {
		imports {
			mavenBom "org.springframework.boot:spring-boot-dependencies:3.4.1"
		}
	}

	repositories { mavenCentral() }

	dependencies {
		compileOnly 'org.projectlombok:lombok'
		annotationProcessor 'org.projectlombok:lombok'
		testImplementation 'org.springframework.boot:spring-boot-starter-test'
	}

	tasks.named('test') {
		useJUnitPlatform()
	}
}