plugins {
	id 'org.springframework.boot' // 실행 가능한 모듈에만 적용
}

dependencies {
	// Web & API
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.7.0'

	// Validation
	implementation 'org.springframework.boot:spring-boot-starter-validation'

	implementation project(':common')
	implementation project(':core-service')
}
